### ISSUE TITLE
License

### ISSUE THREAD

**Issue by thockin** [glycerine/go-unsnap-stream#1]
Is the license for this repo self-written?  Is it possible to license under one of the standard licenses?  We'd like to consider using it in Kubernetes, but legal has a list of licenses that are allowed and "DiY" is not one.

**Comment by glycerine** [comment]
LOL at the cargo cult legal team. Have you read the LICENSE? You probably want to. It answers your question.

In short, it is the MIT license PLUS permission to change the terms of the license to your liking.

So if you don't like the license, change it to one you do like. It doesn't get much clearer.

**Comment by thockin** [comment]
Thanks.  It doesn't say MIT, and I didn't diff it against every possible
license text, and I saw customizations to it.  Thanks.

**Comment by glycerine** [comment]
update: I've changed the license to be MIT after another Googler wrote confused by all the freedom they were granted.
