### ISSUE TITLE
README.md says there are no other streaming Snappy implementations

### ISSUE THREAD

**Issue by nigeltao** [glycerine/go-unsnap-stream#3]
README.md says:

> Strangely, though the streaming format was first proposed in Go[1][2], it was never upated, and I could not locate any other library for Go that would handle the streaming/framed snappy format.

The https://github.com/golang/snappy package can also read the streaming format. As https://godoc.org/github.com/golang/snappy says, "There are actually two Snappy formats... The block format is the Decode and Encode functions and the stream format is the Reader and Writer types."

**Comment by glycerine** [comment]
The README is from 4 years ago. I believe it was true at the time.

**Comment by glycerine** [comment]
@nigeltao Nigel please file a pull request to update the README with appropriate pointers into the currently available functionality in the golang/snappy packages. Thanks!
